IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE [Name] = 'Cast') BEGIN
	DROP TABLE [Cast]
END
IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE [Name] = 'AnimeTag') BEGIN
	DROP TABLE [AnimeTag]
END
IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE [Name] = 'Anime') BEGIN
	DROP TABLE [Anime]
END
IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE [Name] = 'VoiceActor') BEGIN
	DROP TABLE [VoiceActor]
END
IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE [Name] = 'Tag') BEGIN
	DROP TABLE [Tag]
END
IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE [Name] = 'Resolution') BEGIN
	DROP TABLE [Resolution]
END
IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE [Name] = 'Producer') BEGIN
	DROP TABLE [Producer]
END

--出版公司
CREATE TABLE [Producer](
	[ID] INT NOT NULL IDENTITY(1, 1),
	[Name] NVARCHAR(50) NOT NULL,
	[Website] NVARCHAR(255) NULL,
	CONSTRAINT PK_Producer_ID PRIMARY KEY([ID]),
	CONSTRAINT UQ_Producer_Name UNIQUE([Name])
)

--分辨率
CREATE TABLE [Resolution](
	[ID] INT NOT NULL IDENTITY(1, 1),
	[Width] SMALLINT NOT NULL,
	[Height] SMALLINT NOT NULL,
	CONSTRAINT PK_Resolution_ID PRIMARY KEY([ID]),
	CONSTRAINT UQ_Resolution_Res UNIQUE([Width], [Height])
)

--标签
CREATE TABLE [Tag](
	[ID] INT NOT NULL IDENTITY(1, 1),
	[Name] NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_Tag_ID PRIMARY KEY([ID]),
	CONSTRAINT UQ_Tag_Name UNIQUE([Name])
)

--声优
CREATE TABLE [VoiceActor](
	[ID] INT NOT NULL IDENTITY(1, 1),
	[Name] NVARCHAR(20) NOT NULL,
	[Birthday] DATETIME NULL,
	CONSTRAINT PK_VoiceActor_ID PRIMARY KEY([ID]),
	CONSTRAINT UQ_VoiceActor_Name UNIQUE([Name])
)

--动画
CREATE TABLE [Anime](
	[ID] INT NOT NULL IDENTITY(1, 1),
	[Name] NVARCHAR(255) NOT NULL,
    [Comment] NVARCHAR(1000) NULL,
	[Date] DATETIME NOT NULL,
	[ProducerID] INT NOT NULL,
	[ResolutionID] INT NOT NULL,
	CONSTRAINT PK_Anime_ID PRIMARY KEY([ID]),
	CONSTRAINT UQ_Anime_Name UNIQUE([Name]),
	CONSTRAINT FK_Anime_PID FOREIGN KEY([ProducerID]) REFERENCES [Producer]([ID]) ON UPDATE CASCADE,
	CONSTRAINT FK_Anime_RID FOREIGN KEY([ResolutionID]) REFERENCES [Resolution]([ID]) ON UPDATE CASCADE
)

--动画标签
CREATE TABLE [AnimeTag](
	[AID] INT NOT NULL,
	[TID] INT NOT NULL,
	CONSTRAINT PK_AnimeTag_ID PRIMARY KEY([AID], [TID]),
	CONSTRAINT FK_AnimeTag_AID FOREIGN KEY([AID]) REFERENCES [Anime]([ID]) ON UPDATE CASCADE,
	CONSTRAINT FK_AnimeTag_TID FOREIGN KEY([TID]) REFERENCES [Tag]([ID]) ON UPDATE CASCADE
)

--动画配音
CREATE TABLE [Cast](
	[AID] INT NOT NULL,
	[VAID] INT NOT NULL,
	[CharaName] NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_Cast_AID_CharaName  PRIMARY KEY ([AID], [CharaName]),
	CONSTRAINT FK_Cast_AID FOREIGN KEY([AID]) REFERENCES [Anime]([ID]) ON UPDATE CASCADE,
	CONSTRAINT FK_Cast_VAID FOREIGN KEY([VAID]) REFERENCES [VoiceActor]([ID]) ON UPDATE CASCADE
)

